sudo: required
language: java
jdk:
- oraclejdk8
notifications:
  email: false
services:
- docker
script:
# for now avoiding tests because they are based on a real Apache Kafka instance
- mvn package -DskipTests
- curl -s https://raw.githubusercontent.com/EnMasseProject/travis-scripts/master/docker-build.sh
  | bash /dev/stdin enmasseproject/amqp-kafka-bridge .
after_success:
- curl -s https://raw.githubusercontent.com/EnMasseProject/travis-scripts/master/trigger-travis.sh
  | bash /dev/stdin
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: hwWwPg3ifYts5my0XsH//HdXoS4UXPCT5uQPD/LbhY7Pwf05d3/SYIoK51BPZQAKcdt+CtjySZbBVv81RWU5lEsmjKZXTPJt3VagMrCEkED6ZRQlRqqa4JF7HLaxmsi9hkLYmRDhWX2HD0Hr38kmziRqDbeepCIXhh6C319XQKKEq/qN99l3B/crc1tiiVepacT82vTO1bUhyldk0JmnoKhwVf5DxIdXPck/fA8ir1vBqL2nswd0C5s4cpsyJDK/LKBsUVdgg33zHBjLhEajUuyUAuvAEXlv/jzoMbO+GNFdjruCviwJhMH2MJ8MnxOwClFEHPOZrHjTXNwJEpt1G0I07vzwDT9iDiUn1tdcKq2CvwY6joyKmN8uLdUzgL/cY6xsG2qFztzOr6vKAAJo+4VQJL5mziQKGAyIt/HEmre8oDq1UvkSTw9/mBAb66quhDHRbgFN6HVo+LyqUiVOExb202NRw06tYHc78/IFbMla/HTpw2qqIKIhDheVpjiGWPI+hNi9mCeTTThdDA3cHCl5QSULo4z+pEfWed0P005VKlWfQ9wlXBbb2xqtD6ZJfV7bIICBZz8L5442/DgrZpMHu1WV8aFURwjYfyYL6mqWziG0NU/DVAM2yNEydLrZy/WCVrxU+sa9uMwIJyS9onouVXY9SjKprVDImTZIJUc=
  - secure: 25c28hP+PEkx0SlLy28kgQXM7Rs5gyGK6Lnq7i7Bp1Br2KnVs1yS+ZExGXn2VtlHx3gZ5B4a9InxY1URX7ors4xulFY6dGdFF22QJ0sTUNQJV2b0cHd0+SQ3Hkjy69gCOhNOSfGEgNgViuh3Ni5Zcak+GvSrcVyRE8n3Q6eQnywZglDHxWYr8CRqHGpcms7F3rqcCbI0oZ9ukIiNaHYVNtAz2n6Xon3A16w2Y2uarpZTcHtrXagYpPnF/v5l0w4lV+IJsAQXYk7JdkCC6MVYv87sYs7Cw81SGBV8m9OGZELECvAvyRQW+PrtjcwgIoqu2NQHPv+h3Bjq+/+/D/dpyHQRyvkynbd1zCZRVI0/Om6jmjOtX3gzvJm7U4yfh1bXrGjEKiNbqAN+QtdDL7MCBJjfL0T7XIBKiIvsO2vMfzlxJSYoS17sFAr4hBAxrcUr6MjM3eKLRUQ2T/qbJ8rHls8ISEUXcc6It+LXam98wNeYH6RUhMRkQJRSoCfD9aXfniQWbRThd23SMcsznhbdoqvW+JYllUjNf70PH+d9X5wfoWC5gg+F1OIrDxx7Z/hVBe/HJwtc6gV8bXAVDA/9jj4CVDabqW5edlKaeAetsFBcZ9iOwS9MSLhyDmZYNgIBwy0On3irirWjtnxA9G+dHffSi0nHFw8zNQyeZu4jorQ=
  - secure: TodOhLBfs0Y8x1hXm7/J1aJsI20naNGR3vCFoUoky03ZO1aRP7E0RO6KG+SXSh3eiyvWXHhq+ulG0dMQpK4h+Btsrdo0oJb8SU83IlVPZO86w1hosom2QHrjlGjZHlzy4dKnSNHIQJz24L8Aup8Q3nsUIAt8piFDTAAtoBRs0fW579PchtIj9+8GK6DuyAaaKRVp9Z98qOn9rAhzH6f+4uCmVdmZ2C53G16X9nDsiCZ3LUJS/TPzwECvLT2ct1+r4bJZ/PiH6X56b9P9hm7Z8sYQO4a9bfEetgEu4NUHvixQdGKRyKbXcmtRa1HwFh93LHRNpH4bC1tS7zEclb+0WmqJ0uExj+6Hpb4ZRz1NJEY7G6fxPvrDFeB+jj8ejq0smNL/DgVTBafLZaF8S4Dse3qAFgY3tSUgyG4ha/5NN3I2HsRCEFNdSkDZEUHvfhPObMgW80tcwxlXp8kBK8FNvCU7acgIrAxDgS1Ku6AvIjL66JrwyGkPhFBIvGwKC9oEOfzvrZsoZqZ7iimoDrFslxrDccrvNSo1RuqYQmi3fBoVdF++kSHIRBARb8yAOfk/4SF6yxSIKzgX2yXkYx99BXZf2gobN4JWu4Hv+pZxKAtItdxO/OSotd3wmb7uYPmMCziFpZqFTcUf52IbBHDTAq9vmQE+a50FHoRyB//ePHo=
